Q1. What are the benefits of the built-in array package, if any?

Arrays are sequence types and behave very much like lists, 
except that the type of objects stored in them is constrained. 
Built-in array module defines an object type which can efficiently 
represent an array of basic values: characters, integers,
floating point numbers. 
built in array seems to be quite unique.
functions of array are

Get the typecode

get size of array item

append &extend  

array to list

manipulating the index

count no of occurences

Q2. What are some of the array package&#39;s limitations?

An array which is formed will be homogeneous.
That is, in an integer array only integer values can be stored,
while in a float array only floating value and 
character array can have only characters.
Thus, no array can have values of two data types.

Q3. Describe the main differences between the array and numpy packages.

There are several important differences between NumPy arrays 
and the standard Python sequences: 
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). 

Changing the size of an ndarray will create a new array and 
delete the original.

Q4. Explain the distinctions between the empty, ones, and zeros functions.

An empty() function is a function that does not contain any statement witinit body.
zeros() and ones() are numpy functions to create two diffrent arrays.
zeros() function is used to create an array of specified shape and all the values are initialized to zeros.
ones() function is used to create an array of specified shape and all the values are initialized to ones.

Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable
argument?

fromfunction() function construct an array by executing
a function over each coordinate and the resulting array, 
therefore, has a value fn(x, y, z) at coordinate (x, y, z).
Parameters : function : [callable] 
The function is called with N parameters, where N is the rank of shape.

Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as
an int or a floating-point value) through addition, as in the expression A + n?

In [2]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

In [3]:
arr1+5

array([11. , 12.5, 13. ,  5. ,  6. ])

In [ ]:
addition is done for each variable.

In [ ]:
Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)?
What is the outcome?

In [13]:
import numpy as np

a = np.array([1, 2, 3])
b = a + 2
print(b)

[3 4 5]


In [14]:
a = np.array([1,2,3])
b = 3*a
print(b)

[3 6 9]


In [ ]:
Q8. Does a numpy array contain fixed-length strings?
What happens if you allocate a longer string to
one of these arrays?

yes numpy array contain fixed length strings. 
if you allocate a longer string to  one of these arrays ndarray will create a new array and 
delete the original.

Q9. What happens when you combine two numpy arrays using an operation like addition (+) or
multiplication (*)? What are the conditions for combining two numpy arrays?

two numpy array operations like add(), subtract(), multiply() and divison can be performed provided either have same shape

In [3]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [6]:
c = a+b
c

array([5, 4, 5, 8])

In [8]:
d = a-b
d

array([-3,  0,  1,  0])

In [10]:
e = a*b
e

array([ 4,  4,  6, 16])

In [11]:
# arrays of different shape
a = np.array([1,2,3,4])
b = np.array([1,2,3])


In [12]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
Q11. What are three different ways to get the standard deviation of a wide collection of data using
both standard Python and its packages? Sort the three of them by how quickly they execute.

In [15]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [16]:
 x = [8.0, 1, 2.5, 4, 28.0]

In [17]:
n = len(x)
mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n - 1)
var_

123.19999999999999

In [18]:
#Standard deviation
std_ = var_ ** 0.5
std_

11.099549540409285

In [19]:
 std_ = statistics.stdev(x)
 std_


11.099549540409287

In [ ]:
Q12. What is the dimensionality of a Boolean mask-generated array?

In [1]:
import numpy as np
import numpy.ma as ma

In [2]:
arr = np.zeros(7)
print("Array...\n", arr)

Array...
 [0. 0. 0. 0. 0. 0. 0.]


In [3]:
print("\nMasked Array...\n", ma.make_mask(arr))


Masked Array...
 False


In [4]:
print("\nArray Dimensions...\n",arr.ndim)


Array Dimensions...
 1
